name: Build documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@main
    with:
      commit_sha: ${{ github.sha }}
      package: mcp-course
      path_to_docs: units
      build_command: doc-builder build mcp-course units --build_dir build/mcp-course
      deploy_to_hub: true
      languages: en 